name: Release

on:
  push:
    tags:
      - 'v*' # Triggers on v1.0.0, v2.1.3-beta, etc.

permissions:
  contents: write

jobs:
  release:
    name: Release - ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: solo-linux-amd64
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: solo-macos-intel
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: solo-macos-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: solo-windows-amd64.exe

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.job.target }}

    - name: Rust Cache
      uses: swatinem/rust-cache@v2
      with:
        key: ${{ matrix.job.target }}

    - name: Build Binary (Release Mode)
      run: cargo build --release --target ${{ matrix.job.target }}

    - name: Prepare Binary Asset (Unix)
      if: matrix.job.os != 'windows-latest'
      run: |
        cd target/${{ matrix.job.target }}/release
        mv solo ../../../${{ matrix.job.asset_name }}

    - name: Prepare Binary Asset (Windows)
      if: matrix.job.os == 'windows-latest'
      run: |
        cd target/${{ matrix.job.target }}/release
        Move-Item -Path solo.exe -Destination ../../../${{ matrix.job.asset_name }}

    - name: Upload Binaries to Release
      uses: softprops/action-gh-release@v2
      with:
        files: ${{ matrix.job.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}